package main

import (
	"api_techstore/internal/container"
	"api_techstore/internal/models"
	"api_techstore/internal/routes"
	"log"

	_ "api_techstore/docs" // Import docs generated by swag

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title           TechStore API
// @version         1.0
// @description     A TechStore e-commerce API built with Go
// @termsOfService  http://swagger.io/terms/

// @contact.name   API Support
// @contact.url    http://www.swagger.io/support
// @contact.email  support@swagger.io

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:8080
// @BasePath  /api/v1

// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Type "Bearer" followed by a space and JWT token.

func main() {
	// init container
	ctn := container.NewContainer()

	// auto migrate
	if err := ctn.DB.AutoMigrate(
		&models.User{},
		&models.Category{},
		&models.Brand{},
		&models.Product{},
		&models.Order{},
		&models.OrderItem{},
		&models.Address{},
		&models.Payment{},
		&models.Cart{},
		&models.CartItem{},
		&models.ProductImage{},
	); err != nil {
		log.Fatalf("Failed to migrate database: %v", err)
	}

	// init router
	r := gin.Default()
	routes.SetupRouter(r, ctn)

	// Swagger documentation route
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// run server
	r.Run(":8080")
}
